version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gotasker-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - ENVIRONMENT=development
      - DATA_FILE_PATH=/app/data/tasks.json
      - LOG_LEVEL=debug
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - gotasker-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
   image: postgres:15-alpine
   container_name: gotasker-db
   environment:
     POSTGRES_USER: gotasker
     POSTGRES_PASSWORD: password
     POSTGRES_DB: gotasker_db
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   networks:
     - gotasker-network
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U gotasker"]
     interval: 10s
     timeout: 5s
     retries: 5

networks:
  gotasker-network:
    driver: bridge

volumes:
  postgres_data:  # Раскомментируйте для PostgreSQL
